"""
Kamus Slang, Dialek Sunda, Singkatan Pendaki, & Istilah TNGC
Digunakan untuk normalisasi teks sebelum ekstraksi aspek & klasifikasi sentimen.
"""

KAMUS_SLANG_TNGC = {
    # Dialek Sunda & Daerah Ciremai
    "runtah": "sampah",
    "pesing": "bau kotor",
    "ngelekeb": "pengap panas",
    "haseum": "asam bau",
    "tunduh": "mengantuk lelah",
    "cape": "capek lelah",
    "tiris": "dingin sekali",
    "hareudang": "panas gerah",
    "leueur": "licin tergelincir",
    "reungit": "nyamuk",
    "cileuh": "kotor",
    "poek": "gelap",
    "becek": "berlumpur basah",
    "sae": "bagus",
    "rame": "ramai",
    "kumaha": "bagaimana",
    "teu": "tidak",
    "puguh": "pasti jelas",
    "pisan": "banget sekali",
    
    # Istilah Pendakian & TNGC
    "simaksi": "surat izin masuk kawasan konservasi registrasi",
    "tektok": "pendakian cepat tanpa menginap",
    "summit": "menuju puncak",
    "bagas": "babi hutan",
    "pos bayangan": "shelter istirahat",
    "shelter": "pondok pos istirahat",
    "basecamp": "pos registrasi awal",
    "bc": "basecamp",
    "ranger": "petugas pengelola taman nasional",
    "ojek": "transportasi ojek",
    "carter": "sewa angkutan",
    "htm": "harga tiket masuk",
    "tiket": "tiket masuk",
    "pungli": "biaya liar pungutan",
    
    # Singkatan Populer & Slang Medsos / Maps
    "gaada": "tidak ada",
    "gak": "tidak",
    "gk": "tidak",
    "ga": "tidak",
    "tdk": "tidak",
    "ngga": "tidak",
    "nggak": "tidak",
    "bgt": "banget",
    "bgtu": "begitu",
    "bnyk": "banyak",
    "sdh": "sudah",
    "udh": "sudah",
    "udah": "sudah",
    "dgn": "dengan",
    "tp": "tapi",
    "klo": "kalau",
    "kl": "kalau",
    "dr": "dari",
    "krn": "karena",
    "bcs": "karena",
    "bkn": "bukan",
    "sy": "saya",
    "gw": "saya",
    "gue": "saya",
    "loe": "kamu",
    "lu": "kamu",
    "org": "orang",
    "yg": "yang",
    "yng": "yang",
    "d": "di",
    "k": "ke",
    "pd": "pada",
    "bener": "benar",
    "beneran": "benar",
    "rekomen": "rekomendasi",
    "recommended": "rekomendasi bagus",
    "not recommended": "tidak disarankan buruk",
    "slow respon": "pelayanan lambat",
    "jutek": "tidak ramah kasar",
    "parah": "sangat buruk",
    "worth it": "sepadan bagus",
    "zonk": "kecewa buruk",
    "overprice": "terlalu mahal",
    "overpriced": "terlalu mahal",
    "gda": "tidak ada",
    "gada": "tidak ada",
    "bapuk": "rusak jelek",
    "hancur": "rusak parah",
    "kotor bgt": "sangat kotor",
    "msh": "masih"
}
